[2024-06-16T00:54:21.916+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T00:54:22.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.visualization manual__2024-06-16T00:53:51+00:00 [queued]>
[2024-06-16T00:54:22.156+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.visualization manual__2024-06-16T00:53:51+00:00 [queued]>
[2024-06-16T00:54:22.158+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-16T00:54:22.214+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): visualization> on 2024-06-16 00:53:51+00:00
[2024-06-16T00:54:22.272+0000] {standard_task_runner.py:63} INFO - Started process 5345 to run task
[2024-06-16T00:54:22.326+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'visualization', 'manual__2024-06-16T00:53:51+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpdvhhihge']
[2024-06-16T00:54:22.342+0000] {standard_task_runner.py:91} INFO - Job 301: Subtask visualization
[2024-06-16T00:54:22.711+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.visualization manual__2024-06-16T00:53:51+00:00 [running]> on host 6e26965f02f1
[2024-06-16T00:54:23.021+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='visualization' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T00:53:51+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T00:53:51+00:00'
[2024-06-16T00:54:23.024+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T00:54:23.026+0000] {visualization.py:12} INFO - starting data visualization
[2024-06-16T00:54:23.031+0000] {visualization.py:31} ERROR - error visualizing data
Traceback (most recent call last):
  File "/opt/airflow/dags/statistical_analysis/visualization.py", line 15, in visualization
    val_data = pd.read_json(val_data)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 791, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 904, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 944, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 472, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2024-06-16T00:54:23.034+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-16T00:54:23.034+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T00:54:23.058+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Air_pollution_data_pipeline, task_id=visualization, run_id=manual__2024-06-16T00:53:51+00:00, execution_date=20240616T005351, start_date=20240616T005422, end_date=20240616T005423
[2024-06-16T00:54:23.113+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-16T00:54:23.151+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T00:54:23.155+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
