[2024-06-17T04:32:14.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T04:32:14.397+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.avg_emission_by_year manual__2024-06-17T04:27:37+00:00 [queued]>
[2024-06-17T04:32:14.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.avg_emission_by_year manual__2024-06-17T04:27:37+00:00 [queued]>
[2024-06-17T04:32:14.415+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-17T04:32:14.443+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): avg_emission_by_year> on 2024-06-17 04:27:37+00:00
[2024-06-17T04:32:14.452+0000] {standard_task_runner.py:63} INFO - Started process 2395 to run task
[2024-06-17T04:32:14.462+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'avg_emission_by_year', 'manual__2024-06-17T04:27:37+00:00', '--job-id', '453', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmppskytcp_']
[2024-06-17T04:32:14.470+0000] {standard_task_runner.py:91} INFO - Job 453: Subtask avg_emission_by_year
[2024-06-17T04:32:14.768+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.avg_emission_by_year manual__2024-06-17T04:27:37+00:00 [running]> on host fa4d239664b0
[2024-06-17T04:32:15.766+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='avg_emission_by_year' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T04:27:37+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T04:27:37+00:00'
[2024-06-17T04:32:15.768+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T04:32:15.770+0000] {summary_analysis.py:33} INFO - starting average pollutants emission calculation
[2024-06-17T04:32:15.830+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/statistical_analysis/summary_analysis.py:36 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-06-17T04:32:16.281+0000] {summary_analysis.py:45} ERROR - error calculating average emission
Traceback (most recent call last):
  File "/opt/airflow/dags/statistical_analysis/summary_analysis.py", line 39, in avg_emission_by_year
    avg_emision = sub_data.groupby('Year').mean().reset_index()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 9183, in groupby
    return DataFrameGroupBy(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1329, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/groupby/grouper.py", line 1043, in get_grouper
    raise KeyError(gpr)
KeyError: 'Year'
[2024-06-17T04:32:16.287+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T04:32:16.288+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/statistical_analysis/summary_analysis.py", line 39, in avg_emission_by_year
    avg_emision = sub_data.groupby('Year').mean().reset_index()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 9183, in groupby
    return DataFrameGroupBy(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1329, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/groupby/grouper.py", line 1043, in get_grouper
    raise KeyError(gpr)
KeyError: 'Year'
[2024-06-17T04:32:16.303+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=avg_emission_by_year, run_id=manual__2024-06-17T04:27:37+00:00, execution_date=20240617T042737, start_date=20240617T043214, end_date=20240617T043216
[2024-06-17T04:32:16.325+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 453 for task avg_emission_by_year ('Year'; 2395)
[2024-06-17T04:32:16.366+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T04:32:16.405+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T04:32:16.408+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
