[2024-06-16T20:15:22.329+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T20:15:22.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.visualization manual__2024-06-16T20:12:37+00:00 [queued]>
[2024-06-16T20:15:22.769+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.visualization manual__2024-06-16T20:12:37+00:00 [queued]>
[2024-06-16T20:15:22.771+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-16T20:15:22.856+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): visualization> on 2024-06-16 20:12:37+00:00
[2024-06-16T20:15:22.887+0000] {standard_task_runner.py:63} INFO - Started process 7598 to run task
[2024-06-16T20:15:22.947+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'visualization', 'manual__2024-06-16T20:12:37+00:00', '--job-id', '719', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpdnuzf1xn']
[2024-06-16T20:15:23.009+0000] {standard_task_runner.py:91} INFO - Job 719: Subtask visualization
[2024-06-16T20:15:23.435+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.visualization manual__2024-06-16T20:12:37+00:00 [running]> on host 333385971b19
[2024-06-16T20:15:23.852+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='visualization' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T20:12:37+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T20:12:37+00:00'
[2024-06-16T20:15:23.855+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T20:15:23.857+0000] {visualization.py:12} INFO - starting data visualization
[2024-06-16T20:15:23.861+0000] {visualization.py:31} ERROR - error visualizing data
Traceback (most recent call last):
  File "/opt/airflow/dags/statistical_analysis/visualization.py", line 15, in visualization
    val_data = pd.read_json(val_data)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 791, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 904, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 944, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 472, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>
[2024-06-16T20:15:23.866+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-16T20:15:23.867+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T20:15:23.889+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Air_pollution_data_pipeline, task_id=visualization, run_id=manual__2024-06-16T20:12:37+00:00, execution_date=20240616T201237, start_date=20240616T201522, end_date=20240616T201523
[2024-06-16T20:15:24.002+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-16T20:15:24.046+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T20:15:24.050+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
