[2024-06-16T20:23:40.727+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T20:23:40.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.generate_summary manual__2024-06-16T20:06:18+00:00 [queued]>
[2024-06-16T20:23:40.867+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.generate_summary manual__2024-06-16T20:06:18+00:00 [queued]>
[2024-06-16T20:23:40.868+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2024-06-16T20:23:40.923+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): generate_summary> on 2024-06-16 20:06:18+00:00
[2024-06-16T20:23:40.938+0000] {standard_task_runner.py:63} INFO - Started process 8099 to run task
[2024-06-16T20:23:40.954+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'generate_summary', 'manual__2024-06-16T20:06:18+00:00', '--job-id', '824', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp2q7l696v']
[2024-06-16T20:23:40.961+0000] {standard_task_runner.py:91} INFO - Job 824: Subtask generate_summary
[2024-06-16T20:23:41.086+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.generate_summary manual__2024-06-16T20:06:18+00:00 [running]> on host 333385971b19
[2024-06-16T20:23:41.368+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_summary' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T20:06:18+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T20:06:18+00:00'
[2024-06-16T20:23:41.371+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T20:23:41.373+0000] {summary_analysis.py:13} INFO - starting summary statistics of pollutants emission
[2024-06-16T20:23:41.376+0000] {summary_analysis.py:26} ERROR - error calculating pollutants summary statistics
Traceback (most recent call last):
  File "/opt/airflow/dags/statistical_analysis/summary_analysis.py", line 16, in generate_summary
    val_data = pd.read_json(val_data)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 791, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 904, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 944, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 472, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>
[2024-06-16T20:23:41.379+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T20:23:41.381+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/statistical_analysis/summary_analysis.py", line 16, in generate_summary
    val_data = pd.read_json(val_data)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 791, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 904, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 944, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 472, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>
[2024-06-16T20:23:41.399+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=generate_summary, run_id=manual__2024-06-16T20:06:18+00:00, execution_date=20240616T200618, start_date=20240616T202340, end_date=20240616T202341
[2024-06-16T20:23:41.421+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 824 for task generate_summary (Invalid file path or buffer object type: <class 'list'>; 8099)
[2024-06-16T20:23:41.445+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T20:23:41.489+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T20:23:41.492+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
